### PR TITLE
Added @listens tag to jsdoc3.json

### PR DESCRIPTION
**Pull request by ianmcburnie**
Fixes issue #191

### CODE REVIEW

**Comment by apsavin** [comment]
@zxqfox can we merge this?

**Comment by zxqfox** [comment]
Oh, sorry.

**Comment by apsavin** [comment]
Thank you very much! Now you can close https://github.com/jscs-dev/jscs-jsdoc/issues/191 and push a new version to npm)

**Comment by apsavin** [comment]
@zxqfox please-please-please, publish a version. Is there any reason not to do it?

**Comment by zxqfox** [comment]
@apsavin Sorry, v1.3.2 published.

**Comment by apsavin** [comment]
Thank you so very much!;)

**Comment by zxqfox** [comment]
Btw, you don't need to wait for new tags. You can easily add them to your config via extra field:
```
{
  "checkAnnotations": {
    "preset": "jsdoc3",
    "extra": {
      "listens": true
    }
  }
}
```

**Comment by apsavin** [comment]
Sure. Thanks for the tip.

**Pull request merged**
