### PR TITLE
checkReturnTypes: skip checking 'this.something'

### LINKED ISSUE #115: checkReturnTypes for instances
For example

```js
/**
 * Clones current Element structure.
 *
 * @returns {Element}
 */
cloneElement() {
    let clonedChildren = new Array(this._childElements.length);
    for (let i = 0; i < clonedChildren.length; i++) {
        clonedChildren[i] = this._childElements[i].cloneElement();
    }
    return new this.constructor(clonedChildren);
}
```
`checkReturnTypes` will report violation, when it probably shouldn't

### PR DESCRIPTION
**Pull request by zxqfox**
Fixes #115

### CODE REVIEW

**Comment by markelog** [comment]
What about 

```js
return new CreateInstance
```
?

**Comment by zxqfox** [comment]
https://github.com/jscs-dev/jscs-jsdoc/blob/issues/115/test/lib/rules/validate-jsdoc/check-return-types.js#L34-L43 ;-)

**Comment by markelog** [comment]
:+1:

**Pull request closed without merging**
