### PR TITLE
Override is a valid tag

### PR DESCRIPTION
**Pull request by cocoabythefire**
I just ran into a validation issue where `override` was flagged as invalid. I think this is all that's needed to fix that.

### CODE REVIEW

**Comment by ricordisamoa** [comment]
Seems valid. http://usejsdoc.org/tags-override.html

**Comment by alexeykuzmin** [comment]
"override" should be above "overview" in the list )
Maybe it would be easier to merge #178 that fixes the same issue.

**Comment by cocoabythefire** [comment]
@alexeykuzmin thanks - i moved override above.

**Comment by zxqfox** [comment]
Thanks, merged!

**Pull request closed without merging**
